export const types = {
    GET_PLAYERS_TEAM1: 'GET_PLAYERS_TEAM1',
    REQUEST_GET_PLAYERS_TEAM1: 'REQUEST_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1: 'RECEIVE_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1_FAIL: 'RECEIVE_GET_PLAYERS_TEAM1_FAIL',

    GET_PLAYERS_TEAM2: 'GET_PLAYERS_TEAM2',
    REQUEST_GET_PLAYERS_TEAM2: 'REQUEST_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2: 'RECEIVE_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2_FAIL: 'RECEIVE_GET_PLAYERS_TEAM2_FAIL',

    UPDATE_PLAYER: 'UPDATE_PLAYER',
    REQUEST_UPDATE_PLAYER: 'REQUEST_UPDATE_PLAYER',
    RECEIVE_UPDATE_PLAYER: 'RECEIVE_UPDATE_PLAYER',
    RECEIVE_UPDATE_PLAYER_FAIL: 'RECEIVE_UPDATE_PLAYER_FAIL',

    ADD_STATS_TEAM1: 'ADD_STATS_TEAM1',
    REQUEST_ADD_STATS_TEAM1: 'REQUEST_ADD_STATS_TEAM1',
    RECEIVE_ADD_STATS_TEAM1: 'RECEIVE_ADD_STATS_TEAM1',
    RECEIVE_ADD_STATS_TEAM1_FAIL: 'RECEIVE_ADD_STATS_TEAM1_FAIL',

    ADD_STATS_TEAM2: 'ADD_STATS_TEAM2',
    REQUEST_ADD_STATS_TEAM2: 'REQUEST_ADD_STATS_TEAM2',
    RECEIVE_ADD_STATS_TEAM2: 'RECEIVE_ADD_STATS_TEAM2',
    RECEIVE_ADD_STATS_TEAM2_FAIL: 'RECEIVE_ADD_STATS_TEAM2_FAIL',

    ADD_GAME: 'ADD_GAME',
    REQUEST_ADD_GAME: 'REQUEST_ADD_GAME',
    RECEIVE_ADD_GAME: 'RECEIVE_ADD_GAME',
    RECEIVE_ADD_GAME_FAIL: 'RECEIVE_ADD_GAME_FAIL',

    HOST_GAME: 'HOST_GAME',
    REQUEST_HOST_GAME: 'REQUEST_HOST_GAME',
    RECEIVE_HOST_GAME: 'RECEIVE_HOST_GAME',
    RECEIVE_HOST_GAME_FAIL: 'RECEIVE_HOST_GAME_FAIL',

    REQUEST_START_CHANNEL: 'REQUEST_START_CHANNEL',
    RECEIVE_START_CHANNEL: 'RECEIVE_START_CHANNEL',
    RECEIVE_START_CHANNEL_FAIL: 'RECEIVE_START_CHANNEL_FAIL',

    REQUEST_STOP_CHANNEL: 'REQUEST_STOP_CHANNEL',
    RECEIVE_STOP_CHANNEL: 'RECEIVE_STOP_CHANNEL',

    SET_BIG_LOADER: 'SET_BIG_LOADER',

    GET_STATS_LIST_TEAM1: 'GET_STATS_LIST_TEAM1',
    REQUEST_GET_STATS_LIST_TEAM1: 'REQUEST_GET_STATS_LIST_TEAM1',
    RECEIVE_GET_STATS_LIST_TEAM1: 'RECEIVE_GET_STATS_LIST_TEAM1',
    RECEIVE_GET_STATS_LIST_TEAM1_FAIL: 'RECEIVE_GET_STATS_LIST_TEAM1_FAIL',

    GET_STATS_LIST_TEAM2: 'GET_STATS_LIST_TEAM2',
    REQUEST_GET_STATS_LIST_TEAM2: 'REQUEST_GET_STATS_LIST_TEAM2',
    RECEIVE_GET_STATS_LIST_TEAM2: 'RECEIVE_GET_STATS_LIST_TEAM2',
    RECEIVE_GET_STATS_LIST_TEAM2_FAIL: 'RECEIVE_GET_STATS_LIST_TEAM2_FAIL',

    SUCCESSFULL_REFRESH: 'SUCCESSFULL_REFRESH',

    SEND_START_GAME: 'SEND_START_GAME',
    SEND_END_GAME: 'SEND_END_GAME',
}