export const types = {
    GET_PLAYERS_TEAM1: 'GET_PLAYERS_TEAM1',
    REQUEST_GET_PLAYERS_TEAM1: 'REQUEST_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1: 'RECEIVE_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1_FAIL: 'RECEIVE_GET_PLAYERS_TEAM1_FAIL',

    GET_PLAYERS_TEAM2: 'GET_PLAYERS_TEAM2',
    REQUEST_GET_PLAYERS_TEAM2: 'REQUEST_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2: 'RECEIVE_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2_FAIL: 'RECEIVE_GET_PLAYERS_TEAM2_FAIL',
}