export const types = {
    GET_PLAYERS_TEAM1: 'GET_PLAYERS_TEAM1',
    REQUEST_GET_PLAYERS_TEAM1: 'REQUEST_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1: 'RECEIVE_GET_PLAYERS_TEAM1',
    RECEIVE_GET_PLAYERS_TEAM1_FAIL: 'RECEIVE_GET_PLAYERS_TEAM1_FAIL',

    GET_PLAYERS_TEAM2: 'GET_PLAYERS_TEAM2',
    REQUEST_GET_PLAYERS_TEAM2: 'REQUEST_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2: 'RECEIVE_GET_PLAYERS_TEAM2',
    RECEIVE_GET_PLAYERS_TEAM2_FAIL: 'RECEIVE_GET_PLAYERS_TEAM2_FAIL',

    UPDATE_PLAYER: 'UPDATE_PLAYER',
    REQUEST_UPDATE_PLAYER: 'REQUEST_UPDATE_PLAYER',
    RECEIVE_UPDATE_PLAYER: 'RECEIVE_UPDATE_PLAYER',
    RECEIVE_UPDATE_PLAYER_FAIL: 'RECEIVE_UPDATE_PLAYER_FAIL',

    ADD_STATS_TEAM1: 'ADD_STATS_TEAM1',
    REQUEST_ADD_STATS_TEAM1: 'REQUEST_ADD_STATS_TEAM1',
    RECEIVE_ADD_STATS_TEAM1: 'RECEIVE_ADD_STATS_TEAM1',
    RECEIVE_ADD_STATS_TEAM1_FAIL: 'RECEIVE_ADD_STATS_TEAM1_FAIL',

    ADD_STATS_TEAM2: 'ADD_STATS_TEAM2',
    REQUEST_ADD_STATS_TEAM2: 'REQUEST_ADD_STATS_TEAM2',
    RECEIVE_ADD_STATS_TEAM2: 'RECEIVE_ADD_STATS_TEAM2',
    RECEIVE_ADD_STATS_TEAM2_FAIL: 'RECEIVE_ADD_STATS_TEAM2_FAIL',

    ADD_GAME: 'ADD_GAME',
    REQUEST_ADD_GAME: 'REQUEST_ADD_GAME',
    RECEIVE_ADD_GAME: 'RECEIVE_ADD_GAME',
    RECEIVE_ADD_GAME_FAIL: 'RECEIVE_ADD_GAME_FAIL',

    HOST_GAME: 'HOST_GAME',
    REQUEST_HOST_GAME: 'REQUEST_HOST_GAME',
    RECEIVE_HOST_GAME: 'RECEIVE_HOST_GAME',
    RECEIVE_HOST_GAME_FAIL: 'RECEIVE_HOST_GAME_FAIL',

    REQUEST_START_CHANNEL: 'REQUEST_START_CHANNEL',
    RECEIVE_START_CHANNEL: 'RECEIVE_START_CHANNEL',
    RECEIVE_START_CHANNEL_FAIL: 'RECEIVE_START_CHANNEL_FAIL',

    REQUEST_STOP_CHANNEL: 'REQUEST_STOP_CHANNEL',
    RECEIVE_STOP_CHANNEL: 'RECEIVE_STOP_CHANNEL',

    SET_BIG_LOADER: 'SET_BIG_LOADER',

    GET_STATS_LIST_TEAM1: 'GET_STATS_LIST_TEAM1',
    REQUEST_GET_STATS_LIST_TEAM1: 'REQUEST_GET_STATS_LIST_TEAM1',
    RECEIVE_GET_STATS_LIST_TEAM1: 'RECEIVE_GET_STATS_LIST_TEAM1',
    RECEIVE_GET_STATS_LIST_TEAM1_FAIL: 'RECEIVE_GET_STATS_LIST_TEAM1_FAIL',

    GET_STATS_LIST_TEAM2: 'GET_STATS_LIST_TEAM2',
    REQUEST_GET_STATS_LIST_TEAM2: 'REQUEST_GET_STATS_LIST_TEAM2',
    RECEIVE_GET_STATS_LIST_TEAM2: 'RECEIVE_GET_STATS_LIST_TEAM2',
    RECEIVE_GET_STATS_LIST_TEAM2_FAIL: 'RECEIVE_GET_STATS_LIST_TEAM2_FAIL',

    SUCCESSFULL_REFRESH: 'SUCCESSFULL_REFRESH',

    SEND_START_GAME: 'SEND_START_GAME',
    SEND_END_GAME: 'SEND_END_GAME',
    SET_END_GAME: 'SET_END_GAME',
    SET_SOCKET: 'SET_SOCKET',

    SEND_SCORE_1: 'SEND_SCORE_1',
    SEND_SCORE_2: 'SEND_SCORE_2',
    SEND_SCORE_3: 'SEND_SCORE_3',
    
    SEND_MISS_1: 'SEND_MISS_1',
    SEND_MISS_2: 'SEND_MISS_2',
    SEND_MISS_3: 'SEND_MISS_3',
    
    RECEIVE_ADMIN_SCORE_1: 'RECEIVE_ADMIN_SCORE_1',
    RECEIVE_ADMIN_SCORE_2: 'RECEIVE_ADMIN_SCORE_2',
    RECEIVE_ADMIN_SCORE_3: 'RECEIVE_ADMIN_SCORE_3',

    RECEIVE_ADMIN_MISS_1: 'RECEIVE_ADMIN_MISS_1',
    RECEIVE_ADMIN_MISS_2: 'RECEIVE_ADMIN_MISS_2',
    RECEIVE_ADMIN_MISS_3: 'RECEIVE_ADMIN_MISS_3',

    SEND_OFF_REBOUND: 'SEND_OFF_REBOUND',
    SEND_DEF_REBOUND: 'SEND_DEF_REBOUND',
    
    SEND_BLOCKED_SHOT: 'SEND_BLOCKED_SHOT',
    SEND_ASSIST: 'SEND_ASSIST',
    SEND_STEAL: 'SEND_STEAL',
    SEND_TURNOVER: 'SEND_TURNOVER',
    SEND_FOUL: 'SEND_FOUL',
    SEND_FOUL_DRAWN: 'SEND_FOUL_DRAWN',

    SEND_TIMEOUT: 'SEND_TIMEOUT',
    SEND_SUBSTITUTION: 'SEND_SUBSTITUTION',
    RECEIVE_ADMIN_SUBSTITUTION: 'RECEIVE_ADMIN_SUBSTITUTION',

    RECEIVE_ADMIN_STATS_UPDATE: 'RECEIVE_ADMIN_STATS_UPDATE',

        
    SEND_PLAYERS_TIME: 'SEND_PLAYERS_TIME',
    RECEIVE_ADMIN_PLAYERS_TIME: 'RECEIVE_ADMIN_PLAYERS_TIME',

    SEND_CHANGE_QUATER: 'SEND_CHANGE_QUATER',
    RECEIVE_ADMIN_CHANGE_QUATER: 'RECEIVE_ADMIN_CHANGE_QUATER',


}