export const types = {
    GET_LIVE_GAME_LIST: 'GET_LIVE_GAME_LIST',
    REQUEST_GET_LIVE_GAME_LIST: 'REQUEST_GET_LIVE_GAME_LIST',
    RECEIVE_GET_LIVE_GAME_LIST: 'RECEIVE_GET_LIVE_GAME_LIST',
    RECEIVE_GET_LIVE_GAME_LIST_FAIL: 'RECEIVE_GET_LIVE_GAME_LIST_FAIL',

    JOIN_GAME: 'JOIN_GAME',
    REQUEST_JOIN_GAME: 'REQUEST_JOIN_GAME',
    RECEIVE_JOIN_GAME: 'RECEIVE_JOIN_GAME',
    RECEIVE_JOIN_GAME_FAIL: 'RECEIVE_JOIN_GAME_FAIL',

    LEAVE_GAME: 'LEAVE_GAME',
    REQUEST_LEAVE_GAME: 'REQUEST_LEAVE_GAME',
    RECEIVE_LEAVE_GAME: 'RECEIVE_LEAVE_GAME',
    RECEIVE_LEAVE_GAME_FAIL: 'RECEIVE_LEAVE_GAME_FAIL',

    STOP_CHANNEL: 'STOP_CHANNEL',

    SET_GAME: 'SET_GAME',
    SET_ACTIVE_USERS: 'SET_ACTIVE_USERS',

    GET_COMMENT_LIST: 'GET_COMMENT_LIST',
    REQUEST_GET_COMMENT_LIST: 'REQUEST_GET_COMMENT_LIST',
    RECEIVE_GET_COMMENT_LIST: 'RECEIVE_GET_COMMENT_LIST',
    RECEIVE_GET_COMMENT_LIST_FAIL: 'RECEIVE_GET_COMMENT_LIST_FAIL',

    RECEIVE_START_GAME: 'RECEIVE_START_GAME',
    RECEIVE_END_GAME: 'RECEIVE_END_GAME',
    
    RECEIVE_SCORE_1: 'RECEIVE_SCORE_1',
    RECEIVE_SCORE_2: 'RECEIVE_SCORE_2',
    RECEIVE_SCORE_3: 'RECEIVE_SCORE_3',

    RECEIVE_MISS_1: 'RECEIVE_MISS_1',
    RECEIVE_MISS_2: 'RECEIVE_MISS_2',
    RECEIVE_MISS_3: 'RECEIVE_MISS_3',

    RECEIVE_STATS_UPDATE: 'RECEIVE_STATS_UPDATE',
}