export const types = {
    GET_PLAYER_LIST_1: 'GET_PLAYER_LIST_1',
    REQUEST_GET_PLAYER_LIST_1: 'REQUEST_GET_PLAYER_LIST_1',
    RECEIVE_GET_PLAYER_LIST_1: 'RECEIVE_GET_PLAYER_LIST_1',
    RECEIVE_GET_PLAYER_LIST_1_FAIL: 'RECEIVE_GET_PLAYER_LIST_1_FAIL',

    GET_PLAYER_LIST_2: 'GET_PLAYER_LIST_2',
    REQUEST_GET_PLAYER_LIST_2: 'REQUEST_GET_PLAYER_LIST_2',
    RECEIVE_GET_PLAYER_LIST_2: 'RECEIVE_GET_PLAYER_LIST_2',
    RECEIVE_GET_PLAYER_LIST_2_FAIL: 'RECEIVE_GET_PLAYER_LIST_2_FAIL',
}