export const types = {
    GET_PLAYER_LIST_1: 'GET_PLAYER_LIST_1',
    REQUEST_GET_PLAYER_LIST_1: 'REQUEST_GET_PLAYER_LIST_1',
    RECEIVE_GET_PLAYER_LIST_1: 'RECEIVE_GET_PLAYER_LIST_1',
    RECEIVE_GET_PLAYER_LIST_1_FAIL: 'RECEIVE_GET_PLAYER_LIST_1_FAIL',

    GET_PLAYER_LIST_2: 'GET_PLAYER_LIST_2',
    REQUEST_GET_PLAYER_LIST_2: 'REQUEST_GET_PLAYER_LIST_2',
    RECEIVE_GET_PLAYER_LIST_2: 'RECEIVE_GET_PLAYER_LIST_2',
    RECEIVE_GET_PLAYER_LIST_2_FAIL: 'RECEIVE_GET_PLAYER_LIST_2_FAIL',

    GET_STATS_PLAYER_1: 'GET_STATS_PLAYER_1',
    REQUEST_GET_STATS_PLAYER_1: 'REQUEST_GET_STATS_PLAYER_1',
    RECEIVE_GET_STATS_PLAYER_1: 'RECEIVE_GET_STATS_PLAYER_1',
    RECEIVE_GET_STATS_PLAYER_1_FAIL: 'RECEIVE_GET_STATS_PLAYER_1_FAIL',

    GET_STATS_PLAYER_2: 'GET_STATS_PLAYER_2',
    REQUEST_GET_STATS_PLAYER_2: 'REQUEST_GET_STATS_PLAYER_2',
    RECEIVE_GET_STATS_PLAYER_2: 'RECEIVE_GET_STATS_PLAYER_2',
    RECEIVE_GET_STATS_PLAYER_2_FAIL: 'RECEIVE_GET_STATS_PLAYER_2_FAIL',

    GET_STATS_LIST: 'GET_STATS_LIST',
    REQUEST_GET_STATS_LIST: 'REQUEST_GET_STATS_LIST',
    RECEIVE_GET_STATS_LIST: 'RECEIVE_GET_STATS_LIST',
    RECEIVE_GET_STATS_LIST_FAIL: 'RECEIVE_GET_STATS_LIST_FAIL',

    SET_TEAM1: 'SET_TEAM1',
    SET_TEAM2: 'SET_TEAM2',
}