export const types = {
    LOGIN: 'LOGIN',
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RECEIVE_LOGIN: 'RECEIVE_LOGIN',
    RECEIVE_LOGIN_FAIL: 'RECEIVE_LOGIN_FAIL',

    CHECK_TOKEN: 'CHECK_TOKEN',
    REQUEST_CHECK_TOKEN: 'REQUEST_CHECK_TOKEN',
    RECEIVE_CHECK_TOKEN: 'RECEIVE_CHECK_TOKEN',
    RECEIVE_CHECK_TOKEN_FAIL: 'RECEIVE_CHECK_TOKEN_FAIL',

    ADD_USER: 'ADD_USER',
    REQUEST_ADD_USER: 'REQUEST_ADD_USER',
    RECEIVE_ADD_USER: 'RECEIVE_ADD_USER',
    RECEIVE_ADD_USER_FAIL: 'RECEIVE_ADD_USER_FAIL',

    UPDATE_USER: 'UPDATE_USER',
    REQUEST_UPDATE_USER: 'REQUEST_UPDATE_USER',
    RECEIVE_UPDATE_USER: 'RECEIVE_UPDATE_USER',
    RECEIVE_UPDATE_USER_FAIL: 'RECEIVE_UPDATE_USER_FAIL',

    DELETE_USER: 'DELETE_USER',
    REQUEST_DELETE_USER: 'REQUEST_DELETE_USER',
    RECEIVE_DELETE_USER: 'RECEIVE_DELETE_USER',
    RECEIVE_DELETE_USER_FAIL: 'RECEIVE_DELETE_USER_FAIL',

    GET_CURRENT_USER: 'GET_CURRENT_USER',
    REQUEST_GET_CURRENT_USER: 'REQUEST_GET_CURRENT_USER',
    RECEIVE_GET_CURRENT_USER: 'RECEIVE_GET_CURRENT_USER',
    RECEIVE_GET_CURRENT_USER_FAIL: 'RECEIVE_GET_CURRENT_USER_FAIL',

    GET_USER: 'GET_USER',
    REQUEST_GET_USER: 'REQUEST_GET_USER',
    RECEIVE_GET_USER: 'RECEIVE_GET_USER',
    RECEIVE_GET_USER_FAIL: 'RECEIVE_GET_USER_FAIL',

    GET_USER_LIST: 'GET_USER_LIST',
    REQUEST_GET_USER_LIST: 'REQUEST_GET_USER_LIST',
    RECEIVE_GET_USER_LIST: 'RECEIVE_GET_USER_LIST',
    RECEIVE_GET_USER_LIST_FAIL: 'RECEIVE_GET_USER_LIST_FAIL',

    LOGOUT: 'LOGOUT',
    REQUEST_LOGOUT: 'REQUEST_LOGOUT',
    RECEIVE_LOGOUT: 'RECEIVE_LOGOUT',
    RECEIVE_LOGOUT_FAIL: 'RECEIVE_LOGOUT_FAIL',
};