export const types = {
    GET_TEAM_LIST: 'GET_TEAM_LIST',
    REQUEST_GET_TEAM_LIST: 'REQUEST_GET_TEAM_LIST',
    RECEIVE_GET_TEAM_LIST: 'RECEIVE_GET_TEAM_LIST',
    RECEIVE_GET_TEAM_LIST_FAIL: 'RECEIVE_GET_TEAM_LIST_FAIL',
}